### ISSUE TITLE
Permission denied when mounting volumes on CentOS 7

### ISSUE THREAD

**Issue by bahung1221** [gocd/docker-gocd-server#91]
Hi there,

I'm using image `gocd/gocd-server:v22.1.0` with docker-compose, below is my config:

```yml
version: '3'
services:
    gocd-server:
        image: gocd/gocd-server:v22.1.0
        ports:
            - "8153:8153"
            - "8154:8154"
        volumes:
            - ./config/cruise-config.xml:/godata/config/cruise-config.xml
```

As you see, I want to use my old config file, so I mounted it into the container `/godata/config/` folder.
But when I use the volumes option here, a `permission denied` error will occur, this is the log:

```
gocd-server_1   | $ cp -rfv /go-server/config/logback-include.xml /go-working-dir/config/logback-include.xml
gocd-server_1   | cp: can't create '/go-working-dir/config/logback-include.xml': Permission denied
gocd-server_1   | /docker-entrypoint.sh: cannot cp -rfv /go-server/config/logback-include.xml /go-working-dir/config/logback-include.xml
```

I read the blog about the non-root user here, but I don't really understand how to set it up, because the `go` user doesn't exist on our server?
https://www.gocd.org/2019/06/25/GoCD-non-root-containers/

Please can anyone help me to resolve this problem?
Thanks a lot!
